/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/backgrounds`; params?: Router.UnknownInputParams; } | { pathname: `/screens/camera`; params?: Router.UnknownInputParams; } | { pathname: `/screens/filters`; params?: Router.UnknownInputParams; } | { pathname: `/screens/gallery`; params?: Router.UnknownInputParams; } | { pathname: `/screens/interview-mode`; params?: Router.UnknownInputParams; } | { pathname: `/screens/preview-old`; params?: Router.UnknownInputParams; } | { pathname: `/screens/preview`; params?: Router.UnknownInputParams; } | { pathname: `/screens/settings`; params?: Router.UnknownInputParams; } | { pathname: `/screens/template-selection`; params?: Router.UnknownInputParams; } | { pathname: `/screens/video-player`; params?: Router.UnknownInputParams; } | { pathname: `/screens/vision-camera-test`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/backgrounds`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/camera`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/filters`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/gallery`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/interview-mode`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/preview-old`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/preview`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/template-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/video-player`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/vision-camera-test`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/backgrounds${`?${string}` | `#${string}` | ''}` | `/screens/camera${`?${string}` | `#${string}` | ''}` | `/screens/filters${`?${string}` | `#${string}` | ''}` | `/screens/gallery${`?${string}` | `#${string}` | ''}` | `/screens/interview-mode${`?${string}` | `#${string}` | ''}` | `/screens/preview-old${`?${string}` | `#${string}` | ''}` | `/screens/preview${`?${string}` | `#${string}` | ''}` | `/screens/settings${`?${string}` | `#${string}` | ''}` | `/screens/template-selection${`?${string}` | `#${string}` | ''}` | `/screens/video-player${`?${string}` | `#${string}` | ''}` | `/screens/vision-camera-test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/backgrounds`; params?: Router.UnknownInputParams; } | { pathname: `/screens/camera`; params?: Router.UnknownInputParams; } | { pathname: `/screens/filters`; params?: Router.UnknownInputParams; } | { pathname: `/screens/gallery`; params?: Router.UnknownInputParams; } | { pathname: `/screens/interview-mode`; params?: Router.UnknownInputParams; } | { pathname: `/screens/preview-old`; params?: Router.UnknownInputParams; } | { pathname: `/screens/preview`; params?: Router.UnknownInputParams; } | { pathname: `/screens/settings`; params?: Router.UnknownInputParams; } | { pathname: `/screens/template-selection`; params?: Router.UnknownInputParams; } | { pathname: `/screens/video-player`; params?: Router.UnknownInputParams; } | { pathname: `/screens/vision-camera-test`; params?: Router.UnknownInputParams; };
    }
  }
}
